# Generated by Django 5.2.5 on 2025-09-23 03:23

import django.db.models.deletion
import storage.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='資料夾名稱')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='擁有者')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.folder', verbose_name='上層資料夾')),
            ],
            options={
                'verbose_name': '資料夾',
                'verbose_name_plural': '資料夾',
                'unique_together': {('name', 'parent', 'owner')},
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='檔案名稱')),
                ('file', models.FileField(upload_to=storage.models.user_directory_path, verbose_name='檔案')),
                ('file_type', models.CharField(blank=True, max_length=100, verbose_name='檔案類型')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='檔案大小')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上傳時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_shared', models.BooleanField(default=False, verbose_name='是否分享')),
                ('share_token', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='分享代碼')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='擁有者')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.folder', verbose_name='所在資料夾')),
            ],
            options={
                'verbose_name': '檔案',
                'verbose_name_plural': '檔案',
            },
        ),
        migrations.CreateModel(
            name='SharedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='分享代碼')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='到期時間')),
                ('download_count', models.IntegerField(default=0, verbose_name='下載次數')),
                ('max_downloads', models.IntegerField(blank=True, null=True, verbose_name='最大下載次數')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.file', verbose_name='檔案')),
            ],
            options={
                'verbose_name': '分享連結',
                'verbose_name_plural': '分享連結',
            },
        ),
    ]
