# Generated by Django 5.2.5 on 2025-10-01 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='storage_location',
            field=models.CharField(choices=[('disk1', 'D 槽'), ('disk2', 'E 槽'), ('disk3', 'F 槽')], default='disk1', max_length=50, verbose_name='儲存位置'),
        ),
    ]
