# Generated by Django 5.2.5 on 2025-10-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_file_storage_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='storage_location',
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='', verbose_name='檔案'),
        ),
    ]
