# Generated by Django 5.2.5 on 2025-10-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_file_deleted_at_file_is_deleted_folder_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='檔案 Hash'),
        ),
    ]
