# Generated by Django 5.2.5 on 2025-10-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_file_file_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='tags',
            field=models.CharField(blank=True, max_length=500, verbose_name='標籤'),
        ),
    ]
